### PR TITLE
Bring deploy code up to parity w/ Capistrano 2.15.5

### PR DESCRIPTION
**Pull request by jeffbyrnes**
I know that this gem is obsolete, but I ended up hacking this together to fix an issue for myself while I'm still transitioning to Cap 3.

The biggest fix here is for `run_locally`, see [lib/railsless-deploy.rb at line 126](https://github.com/leehambley/railsless-deploy/pull/25/files#diff-52e0e27ca58cdf18fd06c0f9ee11e664R126) for details.

Otherwise, it's just ensuring that no other idiosyncrasies exist between vanilla Cap & railsless-deploy (other than what's by design, of course).

### CODE REVIEW

**Comment by leehambley** [comment]
Sorry Jeff, we're not taking any fixes for cap2. Thanks for reporting this.
If anyone runs into it, at least they'll have your fork! Neat fix.

**Comment by leehambley** [comment]
Hhrrmmm, on second thought... There's no real downside to releasing this.
Should I transfer gem ownership to you?

**Comment by jeffbyrnes** [comment]
@leehambley I'd love to see this released. If that makes the most sense, sure! Happy to take care of updating RubyGems.

**Comment by jeffbyrnes** [comment]
@leehambley not sure if you want to just merge this in & do one last release, or transfer ownership & I'll take care of it. Figured I'd give you one last poke on the topic :smiley:

**Comment by leehambley** [comment]
I thought I had transferred ownership, sorry. I'm on vacation u I'll the
weekend and skiing in the Alps,,connection is spotty so I'll be available
at the weekend.

**Comment by jeffbyrnes** [comment]
@leehambley no worries! And no rush; please enjoy your holiday. Sounds pretty awesome :smiley:

**Comment by leehambley** [comment]
Hi Jeff, I'm back on the map!

## Lee Hambley

http://lee.hambley.name/
+49 (0) 170 298 5667

**Comment by leehambley** [comment]
I can't transfer ownership because you already have a fork, I added you as
a collaborator to the main repo, perhaps that grants you enough access to
transfer the ownership. Either way, ping me back and I'll try again later.

## Lee Hambley

http://lee.hambley.name/
+49 (0) 170 298 5667

**Comment by jeffbyrnes** [comment]
@leehambley I'll see about carrying it forward from here, but yeah, I should have enough access to make it work. Thanks!

**Comment by jeffbyrnes** [comment]
@leehambley ok, I merged this in, and deleted my fork. Should be all set to transfer ownership.

**Comment by leehambley** [comment]
Done!

## Lee Hambley

http://lee.hambley.name/
+49 (0) 170 298 5667

**Comment by jeffbyrnes** [comment]
@leehambley like a yak shave, one last thing to do: [transfer ownership on RubyGems](http://guides.rubygems.org/command-reference/#gem_owner).

I believe the command you'd need to run is: `gem owner railsless-deploy -a 'thejeffbyrnes@gmail.com'`.

Then I think I can quit bugging you about this, heh.

**Comment by leehambley** [comment]
Done!

✗  gem owner railsless-deploy -a 'thejeffbyrnes@gmail.com'
Error loading RubyGems plugin
"/Users/leehambley/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/yard-0.8.3/lib/rubygems_plugin.rb":
cannot load such file -- rubygems/doc_manager (LoadError)
Owner added successfully.
Owners for gem: railsless-deploy
- thejeffbyrnes@gmail.com
- lee.hambley@gmail.com

## Lee Hambley

http://lee.hambley.name/
+49 (0) 170 298 5667

**Pull request merged**
