### PR TITLE
Change ls options to '-xr' to stop nondeterministic deploy:rollback behavior.

### PR DESCRIPTION
**Pull request by randomcamel**
Lee:

We use rsync to deploy code, and it leaves the timestamps all screwy for reasons I can't quite figure, so 'ls -xt' doesn't produce correct results, while 'ls -xr' does.

I understand if this patch won't product correct behavior for people who name their releases differently. If that's the case, please reject it, but would it make sense to provide some user-visible setting to alter the ls options? That seems like a more correct choice, but it's more than a 1-character change. =)

Chris

---

Change ls options from -xt to -xr, which fixes nondeterministic rollback behavior when our releases are named 20110404210241 (YYYYMMDDHHMMSS) but our modification times are unreliable (apparently because of rsync). Best thing would be to have the ls options be user-settable.

### CODE REVIEW

**Comment by leehambley** [comment]
Chris,

Thanks - I might make it an option for Rspec users, something like this is
worth having… maybe we look upstream and see if there's a flag for RSync
which would do the same?
- Lee

**Comment by randomcamel** [comment]
Lee:

I'll be frank, I have no idea how this might be useful to anyone else outside railsless-deploy. :-) It became sort of an urgent thing for me, because without it, deploy:rollback deletes a semi-random release and symlinks back to some other semi-random release. That may or may not be my co-worker's fault with the rsync deploy task we use. It's possible something more general is appropriate, like passing a full Unix command to produce a correctly--ordered list of releases.

Chris

**Comment by koenvw** [comment]
Hi, I came across this also and the nondeterministic behavior has been fixed in capistano by sorting the releases in ruby and not via ls.

See https://github.com/capistrano/capistrano/commit/8638f2278ebe484ebcb1a1950e157c30c2d70960#lib/capistrano/recipes/deploy.rb

**Comment by plentz** [comment]
+1

**Comment by leehambley** [comment]
https://github.com/leehambley/railsless-deploy/commit/8df668b5187910a5ffa97649a29d36453b3922ba

**Pull request closed without merging**
